/**
 * Application Constants
 */

export const RESULT_STATES = {
  CLEAR: 'CLEAR',
  BOUNDARY_VARIANCE: 'BOUNDARY_VARIANCE',
  POTENTIAL_BUILDING_ENCROACHMENT: 'POTENTIAL_BUILDING_ENCROACHMENT',
  INSUFFICIENT_SPATIAL_DATA: 'INSUFFICIENT_SPATIAL_DATA',
}

export const BOUNDARY_STATUS = {
  AUTHORITATIVE: 'AUTHORITATIVE',
  REFERENCE_ONLY: 'REFERENCE_ONLY',
  UNKNOWN: 'UNKNOWN',
}

export const ERROR_CODES = {
  INVALID_GEOMETRY: 'INVALID_GEOMETRY',
  MISSING_PARCEL: 'MISSING_PARCEL',
  MISSING_IMAGE: 'MISSING_IMAGE',
  INVALID_GEOTIFF: 'INVALID_GEOTIFF',
  MISSING_CRS: 'MISSING_CRS',
  INSUFFICIENT_SPATIAL_DATA: 'INSUFFICIENT_SPATIAL_DATA',
  PROCESSING_ERROR: 'PROCESSING_ERROR',
  AI_SERVICE_ERROR: 'AI_SERVICE_ERROR',
  REPORT_GENERATION_ERROR: 'REPORT_GENERATION_ERROR',
}
